export const exampleResponse =                 

{
   "lat":33.44,
   "lon":-94.04,
   "timezone":"America/Chicago",
   "timezone_offset":-18000,
   "current":{
      "dt":1684929490,
      "sunrise":1684926645,
      "sunset":1684977332,
      "temp":292.55,
      "feels_like":292.87,
      "pressure":1014,
      "humidity":89,
      "dew_point":290.69,
      "uvi":0.16,
      "clouds":53,
      "visibility":10000,
      "wind_speed":3.13,
      "wind_deg":93,
      "wind_gust":6.71,
      "weather":[
         {
            "id":803,
            "main":"Clouds",
            "description":"broken clouds",
            "icon":"04d"
         }
      ]
   },
   "minutely":[
      {
         "dt":1684929540,
         "precipitation":0
      },
   ],
   "hourly":[
      {
         "dt":1684926000,
         "temp":292.01,
         "feels_like":292.33,
         "pressure":1014,
         "humidity":91,
         "dew_point":290.51,
         "uvi":0,
         "clouds":54,
         "visibility":10000,
         "wind_speed":2.58,
         "wind_deg":86,
         "wind_gust":5.88,
         "weather":[
            {
               "id":803,
               "main":"Clouds",
               "description":"broken clouds",
               "icon":"04n"
            }
         ],
         "pop":0.15
      },
   ],
   "daily":[
      {
         "dt":1684951200,
         "sunrise":1684926645,
         "sunset":1684977332,
         "moonrise":1684941060,
         "moonset":1684905480,
         "moon_phase":0.16,
         "summary":"Expect a day of partly cloudy with rain",
         "temp":{
            "day":299.03,
            "min":290.69,
            "max":300.35,
            "night":291.45,
            "eve":297.51,
            "morn":292.55
         },
         "feels_like":{
            "day":299.21,
            "night":291.37,
            "eve":297.86,
            "morn":292.87
         },
         "pressure":1016,
         "humidity":59,
         "dew_point":290.48,
         "wind_speed":3.98,
         "wind_deg":76,
         "wind_gust":8.92,
         "weather":[
            {
               "id":500,
               "main":"Rain",
               "description":"light rain",
               "icon":"10d"
            }
         ],
         "clouds":92,
         "pop":0.47,
         "rain":0.15,
         "uvi":9.23
      },
   ],
    "alerts": [
    {
      "sender_name": "NWS Philadelphia - Mount Holly (New Jersey, Delaware, Southeastern Pennsylvania)",
      "event": "Small Craft Advisory",
      "start": 1684952747,
      "end": 1684988747,
      "description": "...SMALL CRAFT ADVISORY REMAINS IN EFFECT FROM 5 PM THIS\nAFTERNOON TO 3 AM EST FRIDAY...\n* WHAT...North winds 15 to 20 kt with gusts up to 25 kt and seas\n3 to 5 ft expected.\n* WHERE...Coastal waters from Little Egg Inlet to Great Egg\nInlet NJ out 20 nm, Coastal waters from Great Egg Inlet to\nCape May NJ out 20 nm and Coastal waters from Manasquan Inlet\nto Little Egg Inlet NJ out 20 nm.\n* WHEN...From 5 PM this afternoon to 3 AM EST Friday.\n* IMPACTS...Conditions will be hazardous to small craft.",
      "tags": [

      ]
    },
  ]
}       



export const exampleResponse2 = {
  lat: 40.7128,
  lon: -74.006,
  timezone: 'America/New_York',
  timezone_offset: -18000,
  current: {
    dt: 1706028202,
    sunrise: 1706012027,
    sunset: 1706047282,
    temp: 3.49,
    feels_like: 0.26,
    pressure: 1034,
    humidity: 64,
    dew_point: -2.36,
    uvi: 0.34,
    clouds: 100,
    visibility: 10000,
    wind_speed: 3.6,
    wind_deg: 270,
    weather: [
      {
         "id":803,
         "main":"Clouds",
         "description":"broken clouds",
         "icon":"04d"
      }
   ],
    rain: { '1h': 0.23 }
  },
}

export const exampleGeoCoding = [
  {
    name: 'London',
    local_names: {
      bg: 'Лондон',
      sr: 'Лондон',
      gn: 'Lóndyre',
      mg: 'Lôndôna',
      sc: 'Londra',
      sh: 'London',
      gu: 'લંડન',
      lo: 'ລອນດອນ',
      ascii: 'London',
      sv: 'London',
      su: 'London',
      km: 'ឡុងដ៍',
      eo: 'Londono',
      am: 'ለንደን',
      pl: 'Londyn',
      tw: 'London',
      kl: 'London',
      ga: 'Londain',
      ie: 'London',
      gl: 'Londres',
      an: 'Londres',
      is: 'London',
      et: 'London',
      mn: 'Лондон',
      ln: 'Lóndɛlɛ',
      uk: 'Лондон',
      sa: 'लन्डन्',
      ne: 'लन्डन',
      sm: 'Lonetona',
      mt: 'Londra',
      bm: 'London',
      ff: 'London',
      es: 'Londres',
      hy: 'Լոնդոն',
      st: 'London',
      sn: 'London',
      jv: 'London',
      ur: 'علاقہ لندن',
      kn: 'ಲಂಡನ್',
      de: 'London',
      ba: 'Лондон',
      fo: 'London',
      sq: 'Londra',
      ml: 'ലണ്ടൻ',
      ca: 'Londres',
      ny: 'London',
      kv: 'Лондон',
      rm: 'Londra',
      to: 'Lonitoni',
      zh: '伦敦',
      bh: 'लंदन',
      id: 'London',
      kk: 'Лондон',
      fi: 'Lontoo',
      ht: 'Lonn',
      tk: 'London',
      gv: 'Lunnin',
      af: 'Londen',
      zu: 'ILondon',
      na: 'London',
      fj: 'Lodoni',
      ms: 'London',
      be: 'Лондан',
      so: 'London',
      co: 'Londra',
      hi: 'लंदन',
      lv: 'Londona',
      vo: 'London',
      hu: 'London',
      lt: 'Londonas',
      te: 'లండన్',
      ig: 'London',
      li: 'Londe',
      az: 'London',
      tr: 'Londra',
      pa: 'ਲੰਡਨ',
      av: 'Лондон',
      cu: 'Лондонъ',
      sd: 'لنڊن',
      bo: 'ལོན་ཊོན།',
      ja: 'ロンドン',
      en: 'London',
      qu: 'London',
      el: 'Λονδίνο',
      ab: 'Лондон',
      sk: 'Londýn',
      eu: 'Londres',
      ko: '런던',
      nn: 'London',
      th: 'ลอนดอน',
      ee: 'London',
      se: 'London',
      wo: 'Londar',
      ta: 'இலண்டன்',
      fr: 'Londres',
      sw: 'London',
      tt: 'Лондон',
      lb: 'London',
      cs: 'Londýn',
      tg: 'Лондон',
      cv: 'Лондон',
      oc: 'Londres',
      mr: 'लंडन',
      om: 'Landan',
      wa: 'Londe',
      he: 'לונדון',
      ce: 'Лондон',
      no: 'London',
      kw: 'Loundres',
      bs: 'London',
      ka: 'ლონდონი',
      ky: 'Лондон',
      nv: 'Tooh Dineʼé Bikin Haalʼá',
      hr: 'London',
      da: 'London',
      mk: 'Лондон',
      ps: 'لندن',
      bn: 'লন্ডন',
      ug: 'لوندۇن',
      fy: 'Londen',
      sl: 'London',
      si: 'ලන්ඩන්',
      pt: 'Londres',
      ay: 'London',
      vi: 'Luân Đôn',
      ru: 'Лондон',
      br: 'Londrez',
      tl: 'Londres',
      mi: 'Rānana',
      or: 'ଲଣ୍ଡନ',
      ro: 'Londra',
      ha: 'Landan',
      it: 'Londra',
      yo: 'Lọndọnu',
      ia: 'London',
      gd: 'Lunnainn',
      feature_name: 'London',
      ar: 'لندن',
      ku: 'London',
      cy: 'Llundain',
      fa: 'لندن',
      yi: 'לאנדאן',
      my: 'လန်ဒန်မြို့',
      nl: 'Londen',
      io: 'London',
      bi: 'London',
      uz: 'London',
      os: 'Лондон'
    },
    lat: 51.5073219,
    lon: -0.1276474,
    country: 'GB',
    state: 'England'
  },
  {
    name: 'City of London',
    local_names: {
      en: 'City of London',
      fr: 'Cité de Londres',
      hi: 'सिटी ऑफ़ लंदन',
      uk: 'Лондонське Сіті',
      ur: 'لندن شہر',
      lt: 'Londono Sitis',
      he: 'הסיטי של לונדון',
      zh: '倫敦市',
      pt: 'Cidade de Londres',
      ko: '시티 오브 런던',
      es: 'City de Londres',
      ru: 'Сити'
    },
    lat: 51.5156177,
    lon: -0.0919983,
    country: 'GB',
    state: 'England'
  },
  {
    name: 'London',
    local_names: {
      bn: 'লন্ডন',
      iu: 'ᓚᓐᑕᓐ',
      th: 'ลอนดอน',
      he: 'לונדון',
      hy: 'Լոնտոն',
      yi: 'לאנדאן',
      oj: 'Baketigweyaang',
      en: 'London',
      ru: 'Лондон',
      lt: 'Londonas',
      ja: 'ロンドン',
      fr: 'London',
      fa: 'لندن',
      cr: 'ᓬᐊᐣᑕᐣ',
      be: 'Лондан',
      el: 'Λόντον',
      ar: 'لندن',
      ko: '런던',
      ga: 'Londain',
      ka: 'ლონდონი',
      ug: 'لوندۇن',
      lv: 'Landona'
    },
    lat: 42.9832406,
    lon: -81.243372,
    country: 'CA',
    state: 'Ontario'
  },
  {
    name: 'Chelsea',
    local_names: {
      no: 'Chelsea',
      pl: 'Chelsea',
      sh: 'Chelsea, London',
      ar: 'تشيلسي',
      nl: 'Chelsea',
      fa: 'چلسی',
      id: 'Chelsea, London',
      sk: 'Chelsea',
      el: 'Τσέλσι',
      tr: 'Chelsea, Londra',
      hu: 'Chelsea',
      eu: 'Chelsea',
      ja: 'チェルシー',
      uk: 'Челсі',
      es: 'Chelsea',
      da: 'Chelsea',
      ga: 'Chelsea',
      af: 'Chelsea, Londen',
      ur: 'چیلسی، لندن',
      et: 'Chelsea',
      fr: 'Chelsea',
      ko: '첼시',
      hi: 'चेल्सी, लंदन',
      he: "צ'לסי",
      pt: 'Chelsea',
      sv: 'Chelsea, London',
      it: 'Chelsea',
      en: 'Chelsea',
      ru: 'Челси',
      vi: 'Chelsea, Luân Đôn',
      zh: '車路士',
      de: 'Chelsea',
      az: 'Çelsi'
    },
    lat: 51.4875167,
    lon: -0.1687007,
    country: 'GB',
    state: 'England'
  },
  {
    name: 'London',
    lat: 37.1289771,
    lon: -84.0832646,
    country: 'US',
    state: 'Kentucky'
  }
]